Repository typedb/typedb-driver, pull requests merged in 2019-09, with the labels that each got.

#33 Adapt to latest @graknlabs_bazel_distribution
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: build

#36 Fix syntax error in the CircleCI workflow
  .circleci/config.yml
Labels: build

#37 Make client-java 1.5.5 releasable by depending on released dependencies
  VERSION
  dependencies/graknlabs/dependencies.bzl
Labels: build

#40 Fix CI by upgrading @graknlabs_build_tools
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build

#38 Behaviour-driven test implementation for client-java - Part 1
  .circleci/config.yml
  GraknClient.java
  WORKSPACE
  common/BUILD
  common/util/Collections.java
  common/util/Streams.java
  common/util/Triple.java
  common/util/Tuple.java
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts/commons-io/BUILD
  dependencies/maven/artifacts/io/cucumber/BUILD
  dependencies/maven/artifacts/junit/BUILD
  dependencies/maven/artifacts/org/apiguardian/BUILD
  dependencies/maven/artifacts/org/zeroturnaround/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  rpc/RequestBuilder.java
  rpc/Transceiver.java
  test/BUILD
  test/GraknClientTest.java
  test/GraknServerRPCMock.java
  test/behaviour/config/BUILD
  test/behaviour/config/TypeRegistry.java
  test/behaviour/connection/BUILD
  test/behaviour/connection/ConnectionSteps.java
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/keyspace/KeyspaceSteps.java
  test/behaviour/connection/keyspace/KeyspaceTest.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/session/SessionSteps.java
  test/behaviour/connection/session/SessionTest.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/connection/transaction/TransactionTest.java
  test/behaviour/debug/BUILD
  test/behaviour/debug/DebugTest.java
  test/behaviour/debug/debug.feature
  test/deployment/pom.xml
  test/setup/BUILD
  test/setup/GraknProperties.java
  test/setup/GraknSetup.java
  test/setup/GraknSetupCore.java
  test/setup/GraknSetupKGMS.java
  test/setup/logback.xml
Labels: in progress
