Repository typedb/typedb-driver, pull requests merged in 2019-10, with the labels that each got.

#39 Break Grakn-Core Dependency
  .circleci/config.yml
  BUILD
  GraknClient.java
  answer/Answer.java
  answer/AnswerGroup.java
  answer/ConceptList.java
  answer/ConceptMap.java
  answer/ConceptSet.java
  answer/ConceptSetMeasure.java
  answer/Explanation.java
  answer/Numeric.java
  concept/Attribute.java
  concept/AttributeType.java
  concept/Concept.java
  concept/ConceptId.java
  concept/Entity.java
  concept/EntityType.java
  concept/GraknConceptException.java
  concept/Label.java
  concept/MetaType.java
  concept/Relation.java
  concept/RelationType.java
  concept/RemoteConcept.java
  concept/Role.java
  concept/Rule.java
  concept/SchemaConcept.java
  concept/Thing.java
  concept/Type.java
  concept/test/BUILD
  rpc/RequestBuilder.java
  rpc/ResponseReader.java
  test/behaviour/concept/BUILD
  test/behaviour/concept/ConceptIT.java
  test/deployment/src/test/java/application/MavenApplicationTest.java
Labels: refactor

#41 Add autoclosable to session
  GraknClient.java
  rpc/RequestBuilder.java
Labels: bug

#42 Add Missing Tx Methods
  GraknClient.java
Labels: bug, refactor

#43 Return Type rather than SchemaConcept in getMetaConcept()
  GraknClient.java
Labels: bug

#44 Readd missing Tx And ConceptMap methods
  GraknClient.java
  answer/ConceptMap.java
Labels: refactor

#45 Re-implement grakn.client.concept.api Interfaces
  BUILD
  GraknClient.java
  answer/AnswerGroup.java
  answer/ConceptList.java
  answer/ConceptMap.java
  answer/ConceptSet.java
  answer/ConceptSetMeasure.java
  concept/AttributeImpl.java
  concept/AttributeTypeImpl.java
  concept/ConceptImpl.java
  concept/EntityImpl.java
  concept/EntityTypeImpl.java
  concept/MetaType.java
  concept/RelationImpl.java
  concept/RelationTypeImpl.java
  concept/RoleImpl.java
  concept/RuleImpl.java
  concept/SchemaConceptImpl.java
  concept/ThingImpl.java
  concept/TypeImpl.java
  concept/api/Attribute.java
  concept/api/AttributeType.java
  concept/api/Concept.java
  concept/api/ConceptId.java
  concept/api/Entity.java
  concept/api/EntityType.java
  concept/api/GraknConceptException.java
  concept/api/Label.java
  concept/api/Relation.java
  concept/api/RelationType.java
  concept/api/Role.java
  concept/api/Rule.java
  concept/api/SchemaConcept.java
  concept/api/Thing.java
  concept/api/Type.java
  rpc/RequestBuilder.java
  rpc/ResponseReader.java
  test/behaviour/concept/ConceptIT.java
Labels: don't merge, refactor

#46 Minor bugfixes
  GraknClient.java
  concept/api/Thing.java
Labels: bug, refactor

#47 Add Apache License header to everything
  .circleci/config.yml
  BUILD
  WORKSPACE
  common/BUILD
  common/util/Collections.java
  common/util/Streams.java
  common/util/Triple.java
  common/util/Tuple.java
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/BUILD
  dependencies/maven/dependencies.yaml
  dependencies/maven/update.sh
  deployment.properties
  test/behaviour/concept/BUILD
  test/behaviour/config/BUILD
  test/behaviour/connection/BUILD
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/debug/BUILD
  test/setup/BUILD
  test/setup/logback.xml
Labels: build

#48 Fix data in generated pom.xml
  BUILD
Labels: bug, build

#50 Adapt to latest changes in bazel-distribution
  .circleci/config.yml
  BUILD
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build

#52 Refactor how version is provided to deployment rules
  .circleci/config.yml
  BUILD
Labels: build, refactor

#53 Migrate `common` to graknlabs/common
  WORKSPACE
  common/BUILD
  common/util/Collections.java
  common/util/Streams.java
  common/util/Triple.java
  common/util/Tuple.java
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/keyspace/KeyspaceSteps.java
Labels: refactor

#55 Delete return void answer from transaction
  GraknClient.java
Labels: bug

#56 Integrate checking for unused Java dependencies
  .circleci/config.yml
  WORKSPACE
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/debug/BUILD
Labels: build, feature
