Repository typedb/typedb-driver, pull requests merged in 2019-08, with the labels that each got.

#28 Update License to 2019
  .circleci/config.yml
  BUILD
  LICENSE
  WORKSPACE
  concept/test/BUILD
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/BUILD
  dependencies/maven/dependencies.yaml
  dependencies/maven/update.sh
  deployment.properties
  test/BUILD
Labels: refactor

#29 Supply authentication credentials for keyspace operations
  GraknClient.java
  dependencies/graknlabs/dependencies.bzl
  rpc/RequestBuilder.java
Labels: feature, refactor

#30 Add Marco and Haikal as the code owners
  .github/CODEOWNERS
Labels: build

#31 CI job now waits for an existing apt process to finish before proceeding
  .circleci/config.yml
Labels: build

#32 Throw correct exception on failures with keyspace operations
  GraknClient.java
Labels: bug, build
