Repository typedb/typedb-driver, pull requests merged in 2019-03, with the labels that each got.

#1 Add grabl-marker for autoupdating
  WORKSPACE
Labels: build

#2 New package address and maven coordinate
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  BUILD
  GraknClient.java
  concept/RemoteAttribute.java
  concept/RemoteAttributeType.java
  concept/RemoteConcept.java
  concept/RemoteEntity.java
  concept/RemoteEntityType.java
  concept/RemoteMetaType.java
  concept/RemoteRelation.java
  concept/RemoteRelationType.java
  concept/RemoteRole.java
  concept/RemoteRule.java
  concept/RemoteSchemaConcept.java
  concept/RemoteThing.java
  concept/RemoteType.java
  concept/test/BUILD
  concept/test/RemoteConceptIT.java
  exception/GraknClientException.java
  rpc/RequestBuilder.java
  rpc/ResponseReader.java
  rpc/Transceiver.java
  test/BUILD
  test/GraknClientIT.java
  test/GraknClientTest.java
  test/GraknServerRPCMock.java
Labels: refactor

#3 Added WORKSPACE name
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  WORKSPACE
  test/GraknClientIT.java
  test/GraknClientTest.java
Labels: build

#10 Add benchmark as transitive dependency
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: bug
