Repository typedb/typedb-driver, pull requests merged in 2020-04, with the labels that each got.

#81 Read rules from the explanation response proto
  answer/ConceptMap.java
  answer/Explanation.java
  dependencies/graknlabs/dependencies.bzl
  rpc/ResponseReader.java
  test/integration/answer/AnswerIT.java
  test/integration/concept/ConceptIT.java
Labels: type: feature

#86 Allow duplicate role players
  concept/Relation.java
  concept/RelationImpl.java
  dependencies/graknlabs/dependencies.bzl
  test/integration/concept/ConceptIT.java
Labels: type: refactor

#88 Upgrade to Bazel 3.0.0
  .bazelrc
  .bazelversion
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#89 Remove references to benchmark
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: type: refactor

#91 Fix attribute type parameter args
  concept/Concept.java
  concept/thing/Attribute.java
  concept/type/AttributeType.java
  test/integration/concept/ConceptIT.java
Labels: priority: high, type: bug

#92 Async iteration
  GraknClient.java
  exception/GraknClientException.java
  rpc/Transceiver.java
Labels: priority: high, type: feature

#93 Update release-validate-deps
  .circleci/config.yml
Labels: type: build
