Repository typedb/typedb-driver, pull requests merged in 2020-07, with the labels that each got.

#134 Depend on grakn artifact
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/dependencies.bzl
  test/assembly/BUILD
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/debug/BUILD
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/integration/answer/BUILD
  test/integration/concept/BUILD
  test/integration/tracing/BUILD
Labels: type: build

#135 Move GraknSetup test infrastructure to common repo
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  test/BUILD
  test/assembly/BUILD
  test/assembly/QueryTest.java
  test/behaviour/connection/BUILD
  test/behaviour/connection/ConnectionSteps.java
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/keyspace/KeyspaceTest.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/session/SessionTest.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionTest.java
  test/behaviour/debug/BUILD
  test/behaviour/debug/DebugTest.java
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/define/DefineTest.java
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/delete/DeleteTest.java
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/get/GetTest.java
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/insert/InsertTest.java
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/match/MatchTest.java
  test/behaviour/graql/language/undefine/BUILD
  test/behaviour/graql/language/undefine/UndefineTest.java
  test/integration/answer/AnswerIT.java
  test/integration/answer/BUILD
  test/integration/concept/BUILD
  test/integration/concept/ConceptIT.java
  test/integration/tracing/BUILD
  test/integration/tracing/TracingIT.java
  test/setup/GraknProperties.java
  test/setup/GraknSetup.java
  test/setup/GraknSetupCore.java
  test/setup/GraknSetupKGMS.java
  test/setup/logback.xml
Labels: priority: blocker, type: build

#137 Use new artifact extract
  .circleci/config.yml
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
  test/BUILD
Labels: type: build

#138 Fix broken master due to bad grakn extract step in CI
  .circleci/config.yml
Labels: priority: blocker

#139 Override all netty deps to 4.1.38.Final
  WORKSPACE
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: blocker, type: bug, type: build

#140 Cleanup WORKSPACE file from extraneous load statements
  WORKSPACE
Labels: priority: high, type: build

#143 Update to be compatible with 2.0 protocol
  BUILD
  GraknClient.java
  answer/ConceptList.java
  answer/ConceptMap.java
  answer/ConceptSet.java
  answer/ConceptSetMeasure.java
  answer/Explanation.java
  concept/Concept.java
  concept/ConceptIID.java
  concept/SchemaConcept.java
  concept/ValueType.java
  concept/impl/ConceptImpl.java
  concept/impl/SchemaConceptImpl.java
  concept/thing/Attribute.java
  concept/thing/Entity.java
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/EntityImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/MetaType.java
  concept/type/RelationType.java
  concept/type/RoleType.java
  concept/type/Rule.java
  concept/type/ThingType.java
  concept/type/Type.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/MetaTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/RuleImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/repositories.bzl
  rpc/RequestBuilder.java
  rpc/ResponseReader.java
  rpc/Transceiver.java
  test/behaviour/connection/ConnectionSteps.java
  test/behaviour/connection/keyspace/KeyspaceSteps.java
  test/behaviour/connection/session/SessionSteps.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/concept/ConceptIT.java
Labels: priority: blocker, type: feature

#144 Collapse all behavour and integration tests into one CircleCI job
  .circleci/config.yml
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/debug/BUILD
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/undefine/BUILD
Labels: priority: high, type: refactor
