Repository typedb/typedb-driver, pull requests merged in 2020-06, with the labels that each got.

#109 Remove implicit relhas
  concept/SchemaConcept.java
  concept/impl/SchemaConceptImpl.java
  concept/thing/Thing.java
  concept/thing/impl/ThingImpl.java
  dependencies/graknlabs/dependencies.bzl
  test/assembly/QueryTest.java
  test/integration/answer/AnswerIT.java
  test/integration/concept/ConceptIT.java
Labels: priority: high, type: feature

#112 Add full async for queries
  GraknClient.java
  dependencies/graknlabs/dependencies.bzl
  rpc/Transceiver.java
  test/assembly/QueryTest.java
  test/behaviour/graql/GraqlSteps.java
  test/deployment/src/test/java/application/MavenApplicationTest.java
  test/integration/answer/AnswerIT.java
  test/integration/tracing/TracingIT.java
Labels: priority: high, type: feature

#114 Bump Protocol - datetime rename
  concept/ValueType.java
  dependencies/graknlabs/dependencies.bzl
  rpc/RequestBuilder.java
Labels: priority: high, type: refactor

#116 Fix error message missing from async queries on commit
  rpc/Transceiver.java
  test/integration/answer/AnswerIT.java
Labels: priority: high, type: bug

#118 Update gRPC to 1.29.0
  dependencies/maven/artifacts/io/grpc/BUILD
  dependencies/maven/artifacts/io/opencensus/BUILD
  dependencies/maven/artifacts/io/perfmark/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: priority: blocker, type: build

#119 Update gRPC, netty, and other related dependencies
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: priority: high, type: build

#123 Reinstate graknlabs dependencies
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#121 Explainable query flag
  GraknClient.java
  dependencies/graknlabs/dependencies.bzl
  rpc/RequestBuilder.java
  test/integration/answer/AnswerIT.java
Labels: priority: high, type: feature

#125 Fix infinite recursion calls
  GraknClient.java
  WORKSPACE
Labels: priority: high, type: bug

#128 Update CI image to Ubuntu 16 and bump Build Tools
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#129 Add new BDD steps for graql language tests
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/debug/debug.feature
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/behaviour/graql/reasoner/explanation/BUILD
  test/behaviour/graql/reasoner/explanation/ExplanationTest.java
Labels: priority: medium, type: refactor
