Repository typedb/typedb-driver, pull requests merged in 2020-05, with the labels that each got.

#96 Migrate ClientJavaE2E from Grakn Core
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  test/assembly/BUILD
  test/assembly/QueryTest.java
  test/integration/concept/ConceptIT.java
Labels: priority: high, type: refactor

#99 Cast meta types to Type base type so that subs is compatible
  concept/type/impl/MetaTypeImpl.java
  test/integration/concept/ConceptIT.java
Labels: priority: high, type: bug

#100 Use release version of tracing
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: bug

#103 Revert to 1.7.x compatible deps and syntax for release
  .circleci/config.yml
  GraknClient.java
  concept/Concept.java
  concept/DataType.java
  concept/thing/Attribute.java
  concept/thing/impl/AttributeImpl.java
  concept/type/AttributeType.java
  concept/type/impl/AttributeTypeImpl.java
  dependencies/graknlabs/dependencies.bzl
  rpc/RequestBuilder.java
  test/assembly/QueryTest.java
  test/integration/concept/ConceptIT.java
Labels: priority: blocker, type: refactor

#104 Fix static tracing not working for async requests
  .circleci/config.yml
  rpc/Transceiver.java
  test/integration/tracing/BUILD
  test/integration/tracing/TracingIT.java
Labels: priority: high, type: bug

#102 Use release version of deps
  VERSION
  dependencies/graknlabs/dependencies.bzl
Labels: type: build

#107 Synchronise with graknlabs master branches
  .circleci/config.yml
  GraknClient.java
  concept/Concept.java
  concept/ValueType.java
  concept/thing/Attribute.java
  concept/thing/impl/AttributeImpl.java
  concept/type/AttributeType.java
  concept/type/impl/AttributeTypeImpl.java
  dependencies/graknlabs/dependencies.bzl
  rpc/RequestBuilder.java
  test/assembly/QueryTest.java
  test/integration/concept/ConceptIT.java
  test/integration/tracing/TracingIT.java
Labels: priority: blocker, type: build, type: refactor

#106 Add 'grakn define throws' to BDD framework, update verification
  .circleci/config.yml
  test/behaviour/debug/BUILD
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/define/BUILD
Labels: priority: medium, type: refactor

#111 Fix metatypes
  GraknClient.java
  test/integration/concept/ConceptIT.java
Labels: priority: blocker, type: bug
