Repository typedb/typedb-driver, pull requests merged in 2020-03, with the labels that each got.

#75 Update license year
  LICENSE
  dependencies/graknlabs/dependencies.bzl
Labels: build

#76 Update LICENSE
  LICENSE
Labels: build

#77 Avoids running `sync-dependencies-snapshot` on user-facing repositories
  .circleci/config.yml
Labels: bug

#79 Add tracing metadata to requests
  dependencies/graknlabs/dependencies.bzl
  rpc/RequestBuilder.java
  rpc/Transceiver.java
Labels: feature

#80 Fix nullpointer when there is a NOOP trace on the thread
  rpc/RequestBuilder.java
Labels: bug

#83 Add sync-deps marker for grabl-tracing
  dependencies/graknlabs/dependencies.bzl
Labels: build
