Repository typedb/typedb-driver, pull requests merged in 2020-11, with the labels that each got.

#182 Remove unnecessary 'final' from parameters
  GraknOptions.java
  common/ProtoBuilder.java
  common/exception/GraknClientException.java
  concept/ConceptManager.java
  concept/answer/Answer.java
  concept/answer/AnswerGroup.java
  concept/answer/AnswerProtoReader.java
  concept/answer/ConceptMap.java
  concept/proto/ConceptProtoBuilder.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/EntityImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/AttributeType.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/RuleImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/repositories.bzl
  query/QueryManager.java
  rpc/GraknClient.java
  rpc/RPCDatabaseManager.java
  rpc/RPCSession.java
  test/behaviour/BehaviourTest.java
  test/behaviour/concept/thing/attribute/AttributeTest.java
  test/behaviour/concept/thing/entity/EntityTest.java
  test/behaviour/concept/thing/relation/RelationTest.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
  test/behaviour/concept/type/attributetype/AttributeTypeTest.java
  test/behaviour/concept/type/entitytype/EntityTypeTest.java
  test/behaviour/concept/type/relationtype/RelationTypeSteps.java
  test/behaviour/concept/type/relationtype/RelationTypeTest.java
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
  test/behaviour/concept/type/thingtype/ThingTypeTest.java
  test/behaviour/connection/database/DatabaseTest.java
  test/behaviour/connection/session/SessionTest.java
  test/behaviour/connection/transaction/TransactionTest.java
  test/behaviour/debug/DebugTest.java
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/define/DefineTest.java
  test/behaviour/graql/language/delete/DeleteTest.java
  test/behaviour/graql/language/get/GetTest.java
  test/behaviour/graql/language/insert/InsertTest.java
  test/behaviour/graql/language/match/MatchTest.java
  test/behaviour/graql/language/undefine/UndefineTest.java
  test/integration/ClientQueryTest.java
Labels: priority: low, type: refactor

#185 Receiving batched answers from one GRPC message
  .grabl/automation.yml
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/update.sh
  query/QueryManager.java
  rpc/QueryIterator.java
  rpc/RPCTransaction.java
Labels: type: feature

#184 Fix thread safety, data & memory usage issues
  .grabl/automation.yml
  dependencies/graknlabs/repositories.bzl
  rpc/RPCTransaction.java
  test/BUILD
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/type/attributetype/BUILD
  test/behaviour/concept/type/entitytype/BUILD
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/debug/BUILD
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/integration/BUILD
Labels: priority: high, type: bug

#188 Upgrade gRPC to 1.33
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: high, type: build
