Repository typedb/typedb-driver, pull requests merged in 2020-09, with the labels that each got.

#165 Implement missing race condition fix from master
  rpc/Transceiver.java
Labels: priority: high, type: bug

#166 Set up release for 1.8.3
  .circleci/config.yml
  VERSION
Labels: priority: high

#170 Verify license headers
  .bazelignore
  .bazelrc
  .gitignore
  BUILD
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/BUILD
  dependencies/maven/update.sh
  test/BUILD
  test/behaviour/BUILD
  test/behaviour/concept/BUILD
  test/behaviour/concept/thing/BUILD
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/type/attributetype/BUILD
  test/behaviour/concept/type/entitytype/BUILD
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/config/BUILD
  test/behaviour/connection/BUILD
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/keyspace/KeyspaceSteps.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/debug/BUILD
  test/behaviour/debug/debug.feature
  test/behaviour/graql/BUILD
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/behaviour/util/BUILD
  test/deployment/pom.xml
  test/deployment/src/test/java/application/MavenApplicationTest.java
  test/deployment/src/test/resources/logback-test.xml
  test/integration/BUILD
Labels: priority: medium, type: build

#164 More cleanup and bugfixes
  Grakn.java
  GraknOptions.java
  common/exception/ErrorMessage.java
  common/exception/GraknClientException.java
  concept/Concept.java
  concept/Concepts.java
  concept/answer/Answer.java
  concept/answer/AnswerProtoReader.java
  concept/answer/ConceptMap.java
  concept/proto/ConceptProtoBuilder.java
  concept/thing/Attribute.java
  concept/thing/Thing.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/EntityImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/AttributeType.java
  concept/type/Type.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/RuleImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/repositories.bzl
  rpc/GraknClient.java
  rpc/RPCDatabase.java
  rpc/RPCDatabaseManager.java
  rpc/RPCIterator.java
  rpc/RPCTransaction.java
  rpc/RPCTransceiver.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
  test/behaviour/connection/ConnectionSteps.java
  test/behaviour/util/Util.java
  test/deployment/pom.xml
  test/integration/ClientQueryTest.java
Labels: priority: low, type: bug

#171 Even more cleanup and bugfixes
  .grabl/automation.yml
  concept/Concept.java
  concept/Concepts.java
  concept/answer/AnswerGroup.java
  concept/answer/ConceptMap.java
  concept/thing/Attribute.java
  concept/thing/Entity.java
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/EntityImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/RelationType.java
  concept/type/RoleType.java
  concept/type/Rule.java
  concept/type/ThingType.java
  concept/type/Type.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/RuleImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  rpc/RPCTransceiver.java
  test/behaviour/concept/thing/ThingSteps.java
  test/behaviour/concept/thing/entity/EntitySteps.java
  test/behaviour/concept/thing/relation/RelationSteps.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/ClientQueryTest.java
Labels: priority: medium, type: refactor
