Repository typedb/typedb-driver, pull requests merged in 2020-08, with the labels that each got.

#145 Add concept BDD tests and remove old integration tests
  .circleci/config.yml
  GraknClient.java
  README.md
  concept/type/AttributeType.java
  concept/type/RoleType.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  test/assembly/QueryTest.java
  test/behaviour/concept/thing/BUILD
  test/behaviour/concept/thing/ThingSteps.java
  test/behaviour/concept/thing/attribute/AttributeSteps.java
  test/behaviour/concept/thing/attribute/AttributeTest.java
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/entity/EntitySteps.java
  test/behaviour/concept/thing/entity/EntityTest.java
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/thing/relation/RelationSteps.java
  test/behaviour/concept/thing/relation/RelationTest.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
  test/behaviour/concept/type/attributetype/AttributeTypeTest.java
  test/behaviour/concept/type/attributetype/BUILD
  test/behaviour/concept/type/entitytype/BUILD
  test/behaviour/concept/type/entitytype/EntityTypeSteps.java
  test/behaviour/concept/type/entitytype/EntityTypeTest.java
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/relationtype/RelationTypeSteps.java
  test/behaviour/concept/type/relationtype/RelationTypeTest.java
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
  test/behaviour/concept/type/thingtype/ThingTypeTest.java
  test/behaviour/config/Parameters.java
  test/behaviour/connection/ConnectionSteps.java
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/database/DatabaseSteps.java
  test/behaviour/connection/database/DatabaseTest.java
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/keyspace/KeyspaceSteps.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/session/SessionSteps.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/debug/BUILD
  test/behaviour/debug/debug.feature
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/integration/answer/AnswerIT.java
  test/integration/concept/BUILD
  test/integration/concept/ConceptIT.java
  test/integration/tracing/BUILD
  test/integration/tracing/TracingIT.java
Labels: priority: high, type: build

#149 Migrate Client Tests From Core
  dependencies/graknlabs/repositories.bzl
  test/assembly/QueryTest.java
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/keyspace/KeyspaceSteps.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/answer/AnswerIT.java
Labels: priority: medium, type: refactor

#151 Prepare for 1.8.2 Release
  VERSION
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: blocker, type: build

#152 Refactor client-java to use new Graql, new Common and new test server
  BUILD
  GraknClient.java
  answer/ConceptMap.java
  dependencies/graknlabs/repositories.bzl
  rpc/ResponseReader.java
  test/assembly/BUILD
  test/assembly/QueryTest.java
  test/behaviour/concept/thing/BUILD
  test/behaviour/concept/thing/attribute/AttributeTest.java
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/entity/EntityTest.java
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/thing/relation/RelationTest.java
  test/behaviour/concept/type/attributetype/AttributeTypeTest.java
  test/behaviour/concept/type/attributetype/BUILD
  test/behaviour/concept/type/entitytype/BUILD
  test/behaviour/concept/type/entitytype/EntityTypeTest.java
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/relationtype/RelationTypeTest.java
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/concept/type/thingtype/ThingTypeTest.java
  test/behaviour/config/BUILD
  test/behaviour/connection/BUILD
  test/behaviour/connection/ConnectionSteps.java
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/database/DatabaseSteps.java
  test/behaviour/connection/database/DatabaseTest.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/session/SessionSteps.java
  test/behaviour/connection/session/SessionTest.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/connection/transaction/TransactionTest.java
  test/behaviour/debug/DebugTest.java
  test/behaviour/graql/BUILD
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/define/DefineTest.java
  test/behaviour/graql/language/delete/DeleteTest.java
  test/behaviour/graql/language/get/GetTest.java
  test/behaviour/graql/language/insert/InsertTest.java
  test/behaviour/graql/language/match/MatchTest.java
  test/behaviour/graql/language/undefine/UndefineTest.java
  test/behaviour/util/BUILD
Labels: priority: high, type: refactor

#150 Split Relation.players into 2 methods: one filtered by roles, and one that isn't; and replace Role with RoleType in Thing classes
  .circleci/config.yml
  GraknClient.java
  concept/Concept.java
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/RelationType.java
  concept/type/RoleType.java
  concept/type/ThingType.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  dependencies/graknlabs/repositories.bzl
  rpc/RequestBuilder.java
  test/behaviour/concept/thing/relation/RelationSteps.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/concept/.gitkeep
  test/integration/concept/ConceptIT.java
Labels: priority: high, type: bug

#158 Update usage of assemble-maven and patch dependencies to enable a snapshot release ## PATCH ##
  .circleci/config.yml
  BUILD
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.bzl
  test/assembly/QueryTest.java
  test/behaviour/connection/ConnectionSteps.java
  test/behaviour/connection/keyspace/BUILD
  test/behaviour/connection/keyspace/KeyspaceSteps.java
  test/behaviour/connection/keyspace/KeyspaceTest.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/session/SessionSteps.java
  test/behaviour/connection/session/SessionTest.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/connection/transaction/TransactionTest.java
  test/behaviour/debug/DebugTest.java
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/define/DefineTest.java
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/delete/DeleteTest.java
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/get/GetTest.java
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/insert/InsertTest.java
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/match/MatchTest.java
  test/behaviour/graql/language/undefine/BUILD
  test/behaviour/graql/language/undefine/UndefineTest.java
  test/integration/answer/AnswerIT.java
  test/integration/concept/ConceptIT.java
  test/integration/tracing/TracingIT.java
Labels: priority: high, type: refactor

#160 Add Automation YAML in 2.0
  .bazelrc
  .grabl/automation.yml
Labels: priority: high, type: build
