Repository typedb/typedb-driver, pull requests merged in 2020-12, with the labels that each got.

#189 Unused code cleanup and streaming fixes
  Grakn.java
  common/exception/ErrorMessage.java
  concept/ConceptManager.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/EntityImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/ThingType.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/RuleImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/artifacts.bzl
  rpc/QueryFuture.java
  rpc/QueryIterator.java
  rpc/RPCTransaction.java
Labels: priority: medium, type: bug

#191 Minor refactors and restructures in Concept
  .grabl/automation.yml
  concept/ConceptManager.java
  concept/logic/Rule.java
  concept/logic/impl/RuleImpl.java
  concept/proto/ConceptProtoBuilder.java
  concept/type/AttributeType.java
  concept/type/RelationType.java
  concept/type/RoleType.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: refactor

#195 Update grakn core artifact + minor refactorings
  concept/thing/impl/ThingImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/artifacts.bzl
  rpc/RPCTransaction.java
  rpc/ResponseIterator.java
Labels: dependencies, priority: medium, type: build

#199 Update protocol to extract out LogicManager + Session pulse
  BUILD
  Grakn.java
  concept/ConceptManager.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  logic/LogicManager.java
  logic/Rule.java
  logic/impl/RuleImpl.java
  rpc/RPCSession.java
  rpc/RPCTransaction.java
Labels: type: refactor

#196 Update BDD resource clean up strategy
  dependencies/graknlabs/repositories.bzl
  test/behaviour/connection/ConnectionSteps.java
Labels: type: refactor

#198 Split up ProtoBuilder into Grakn and Tracing
  GraknProtoBuilder.java
  common/tracing/TracingProtoBuilder.java
  concept/ConceptManager.java
  logic/LogicManager.java
  query/QueryManager.java
  rpc/RPCSession.java
  rpc/RPCTransaction.java
Labels: priority: low, type: refactor

#200 Make session pulse respect isAlive flag
  rpc/RPCSession.java
Labels: priority: low, type: bug

#201 Update enum casing in accordance with protocol
  concept/proto/ConceptProtoBuilder.java
  concept/type/AttributeType.java
  dependencies/graknlabs/repositories.bzl
Labels: priority: low, type: refactor

#204 Update protocol: repeated fields now pluralised
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/repositories.bzl
  logic/impl/RuleImpl.java
  query/QueryManager.java
Labels: priority: low, type: refactor

#206 Fix a race condition in the timer
  rpc/RPCSession.java
Labels: type: bug

#207 Build Java code to be compatible with older Java
  .bazelrc
Labels: priority: high, type: build

#208 Stop processing responses after the transaction is closed
  rpc/RPCTransaction.java
Labels: type: bug

#209 Update RPCTransaction error handling
  rpc/RPCTransaction.java
Labels: type: bug, type: refactor

#210 Adapt to new grabl
  .grabl/automation.yml
Labels: priority: high, type: build, type: refactor

#212 Close all requests when the transaction stream is closed
  rpc/RPCTransaction.java
Labels: type: bug, type: refactor

#214 Make flaky tests use debug mode grakn runner
  .grabl/automation.yml
  dependencies/graknlabs/repositories.bzl
  test/behaviour/BehaviourTest.java
Labels: type: refactor

#211 Make getSupertypes() return all supertypes, including 'thing'
  concept/ConceptManager.java
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/RelationType.java
  concept/type/RoleType.java
  concept/type/ThingType.java
  concept/type/Type.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
  test/behaviour/concept/thing/ThingSteps.java
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
Labels: type: bug
