Repository typedb/typedb-driver, pull requests merged in 2021-09, with the labels that each got.

#350 User token mechanism for faster authentication
  api/connection/user/User.java
  api/connection/user/UserManager.java
  common/BUILD
  common/exception/ErrorMessage.java
  common/exception/TypeDBClientException.java
  common/rpc/RequestBuilder.java
  common/rpc/TypeDBStub.java
  connection/TypeDBClientImpl.java
  connection/TypeDBConnectionFactory.java
  connection/cluster/ClusterClient.java
  connection/cluster/ClusterDatabaseManager.java
  connection/cluster/ClusterServerClient.java
  connection/cluster/ClusterServerConnectionFactory.java
  connection/cluster/ClusterServerStub.java
  connection/cluster/ClusterUser.java
  connection/cluster/ClusterUserManager.java
  connection/core/CoreClient.java
  connection/core/CoreConnectionFactory.java
  connection/core/CoreStub.java
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/behaviour/connection/user/UserSteps.java
Labels: type: feature

#352 Fix error doing concurrent reads on Java 14-16
  stream/ResponseCollector.java
Labels: type: bug, priority: high

#353 Use ZoneOffset.UTC instead of ZoneId.of("Z")
  common/rpc/RequestBuilder.java
  concept/thing/AttributeImpl.java
Labels: type: bug, priority: medium
