Repository typedb/typedb-driver, pull requests merged in 2021-02, with the labels that each got.

#255 Split the BDD CI job into smaller, more manageable jobs
  .grabl/automation.yml
Labels: type: refactor

#258 Supply artifacts for all platforms to tests
  dependencies/graknlabs/repositories.bzl
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/type/attributetype/BUILD
  test/behaviour/concept/type/entitytype/BUILD
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/behaviour/rules.bzl
Labels: priority: blocker, type: bug

#260 Repair integration artifacts
  test/behaviour/debug/BUILD
  test/integration/BUILD
Labels: type: bug

#256 Update format of Bazel test targets and fix minor issues
  common/exception/ErrorMessage.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  rpc/cluster/RPCSessionCluster.java
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/type/attributetype/BUILD
  test/behaviour/concept/type/entitytype/BUILD
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/debug/BUILD
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/behaviour/rules.bzl
  test/integration/BUILD
Labels: priority: medium, type: refactor

#259 Updater test steps
  .grabl/automation.yml
  dependencies/graknlabs/repositories.bzl
  test/behaviour/concept/thing/relation/RelationSteps.java
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/update/BUILD
  test/behaviour/graql/language/update/UpdateTest.java
Labels: type: feature

#261 Refine the logic for performing primary replica failover
  rpc/cluster/RPCGraknClientCluster.java
  rpc/cluster/RPCSessionCluster.java
Labels: type: bug, type: refactor

#262 Make DatabaseManager more fault tolerant in Cluster
  .bazelrc
  GraknClient.java
  common/exception/ErrorMessage.java
  dependencies/graknlabs/repositories.bzl
  rpc/cluster/RPCDatabaseManagerCluster.java
  rpc/cluster/RPCGraknClientCluster.java
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/database/DatabaseTestCluster.java
  test/behaviour/connection/database/DatabaseTestCore.java
Labels: priority: medium, type: feature

#265 Bind Cluster sessions to single server nodes, and add naive load balancing
  common/exception/GraknClientException.java
  dependencies/graknlabs/repositories.bzl
  rpc/cluster/Address.java
  rpc/cluster/FailsafeTask.java
  rpc/cluster/RPCDatabaseManagerCluster.java
  rpc/cluster/RPCGraknClientCluster.java
  rpc/cluster/RPCSessionCluster.java
  rpc/cluster/ReplicaInfo.java
  rpc/cluster/ServerAddress.java
Labels: priority: medium, type: feature

#266 Rename RPC classes to organise them better
  GraknClient.java
  concept/ConceptManager.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/impl/TypeImpl.java
  logic/LogicManager.java
  logic/impl/RuleImpl.java
  query/QueryManager.java
  rpc/ClientRPC.java
  rpc/DatabaseManagerRPC.java
  rpc/QueryFuture.java
  rpc/ResponseIterator.java
  rpc/SessionRPC.java
  rpc/TransactionRPC.java
  rpc/cluster/ClientClusterRPC.java
  rpc/cluster/DatabaseManagerClusterRPC.java
  rpc/cluster/FailsafeTask.java
  rpc/cluster/SessionClusterRPC.java
Labels: priority: medium, type: refactor

#267 Upgrade to latest @graknlabs_dependencies
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#269 Clean up FailsafeTask
  rpc/cluster/ClientClusterRPC.java
  rpc/cluster/FailsafeTask.java
  rpc/cluster/ReplicaInfo.java
  rpc/cluster/SessionClusterRPC.java
Labels: priority: low, type: refactor

#270 Expose replica info when getting Cluster databases
  .grabl/automation.yml
  GraknClient.java
  common/exception/ErrorMessage.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  rpc/ClientRPC.java
  rpc/DatabaseManagerRPC.java
  rpc/DatabaseRPC.java
  rpc/SessionRPC.java
  rpc/cluster/ClientClusterRPC.java
  rpc/cluster/DatabaseClusterRPC.java
  rpc/cluster/DatabaseManagerClusterRPC.java
  rpc/cluster/FailsafeTask.java
  rpc/cluster/ReplicaInfo.java
  rpc/cluster/ServerAddress.java
  rpc/cluster/SessionClusterRPC.java
  rpc/util/RPCUtils.java
  test/behaviour/connection/ConnectionStepsBase.java
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/database/DatabaseSteps.java
  test/behaviour/connection/session/SessionSteps.java
  test/integration/ClientQueryTest.java
Labels: priority: high, type: feature

#272 Print inner exception when client fails to connect to Grakn
  common/exception/GraknClientException.java
  dependencies/graknlabs/artifacts.bzl
Labels: priority: low, type: bug

#273 Make Database.toString always just return the DB name, even in Cluster
  GraknClient.java
  common/exception/ErrorMessage.java
  rpc/ClientRPC.java
  rpc/cluster/ClientClusterRPC.java
  rpc/cluster/DatabaseClusterRPC.java
Labels: priority: low, type: bug

#274 Update Grakn Core artifact
  dependencies/graknlabs/artifacts.bzl
Labels: priority: high, type: build

#276 Make DatabaseCluster.toString print the database name
  rpc/cluster/DatabaseClusterRPC.java
Labels: priority: low, type: bug

#278 Fix client-java throwing exception when multiple queries run in parallel inside one transaction
  rpc/ResponseIterator.java
  rpc/SynchronizedStreamObserver.java
  rpc/TransactionRPC.java
  test/integration/ClientQueryTest.java
Labels: type: bug

#280 Upgrade common and dependencies
  dependencies/graknlabs/repositories.bzl
  test/BUILD
  test/behaviour/BUILD
  test/behaviour/connection/BUILD
  test/behaviour/connection/ConnectionStepsCore.java
  test/behaviour/connection/database/BUILD
  test/behaviour/debug/BUILD
  test/behaviour/rules.bzl
  test/integration/BUILD
Labels: type: build

#279 Fix exceptions creating Cluster transactions
  common/exception/GraknClientException.java
  rpc/cluster/FailsafeTask.java
Labels: priority: high, type: bug

#282 Make 'all nodes failed' error more readable in Cluster DatabaseManager
  common/exception/ErrorMessage.java
  rpc/cluster/DatabaseManagerClusterRPC.java
Labels: priority: low, type: feature

#281 Add option to enable inference tracing
  GraknOptions.java
  common/proto/OptionsProtoBuilder.java
  dependencies/graknlabs/repositories.bzl
Labels: type: feature

#283 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature

#286 Prepare for alpha-10 release
  VERSION
  dependencies/graknlabs/repositories.bzl
Labels: type: build

#284 Client tracks and closes its sessions when closed
  dependencies/graknlabs/artifacts.bzl
  rpc/ClientRPC.java
  rpc/SessionRPC.java
  test/behaviour/connection/ConnectionStepsBase.java
Labels: priority: medium, type: feature

#285 Recover faster from temporary network outages and server failures
  rpc/ClientRPC.java
  rpc/DatabaseManagerRPC.java
  rpc/DatabaseRPC.java
  rpc/SessionRPC.java
  rpc/TransactionRPC.java
  rpc/cluster/DatabaseManagerClusterRPC.java
  rpc/util/RPCUtils.java
Labels: priority: high, type: bug

#287 Store more complete cluster address information
  common/exception/ErrorMessage.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  rpc/cluster/ServerAddress.java
Labels: priority: high, type: feature

#288 Delete legacy ServerAddress constructor
  rpc/cluster/ServerAddress.java
Labels: priority: medium, type: refactor
