Repository typedb/typedb-driver, pull requests merged in 2021-05, with the labels that each got.

#329 Upgrade @rules_antlr usage
  WORKSPACE
  dependencies/vaticle/repositories.bzl
Labels: type: build

#331 Update usage of rules_antlr
  WORKSPACE
  dependencies/vaticle/repositories.bzl
Labels: priority: high, type: build

#333 Make TypeDB Cluster client require TypeDBCredential
  TypeDB.java
  api/TypeDBCredential.java
  api/TypeDBOptions.java
  cluster/ClusterClient.java
  cluster/ClusterNodeClient.java
  core/CoreClient.java
Labels: type: refactor
