Repository typedb/typedb-driver, pull requests merged in 2021-01, with the labels that each got.

#216 API cleanup: close on commit, isX/asX methods
  concept/Concept.java
  concept/impl/ConceptImpl.java
  concept/proto/ConceptProtoBuilder.java
  concept/thing/Attribute.java
  concept/thing/Entity.java
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/ThingImpl.java
  concept/type/AttributeType.java
  concept/type/Type.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  rpc/RPCTransaction.java
  test/behaviour/graql/GraqlSteps.java
Labels: priority: medium, type: refactor

#217 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#219 Move GraknClient to root package
  GraknClient.java
  concept/answer/ConceptMap.java
  concept/proto/ConceptProtoBuilder.java
  rpc/RPCDatabaseManager.java
  rpc/RPCSession.java
  test/behaviour/connection/ConnectionSteps.java
  test/deployment/src/test/java/application/MavenApplicationTest.java
  test/integration/ClientQueryTest.java
Labels: priority: high, type: refactor

#220 Temporarily disable dependency-analysis
  .grabl/automation.yml
Labels: priority: low, type: build

#218 RPC implementation for sending match aggregate, match group, and match group aggregate queries
  common/exception/ErrorMessage.java
  concept/answer/Answer.java
  concept/answer/AnswerProtoReader.java
  concept/answer/ConceptMap.java
  concept/answer/ConceptMapGroup.java
  concept/answer/Numeric.java
  concept/answer/NumericGroup.java
  concept/impl/ConceptImpl.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  query/QueryManager.java
  test/behaviour/graql/GraqlSteps.java
Labels: type: feature

#222 Fix invalid cast for the super type of root types
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/RelationType.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  dependencies/graknlabs/repositories.bzl
  test/behaviour/connection/database/DatabaseSteps.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/session/SessionSteps.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/util/BUILD
  test/behaviour/util/Util.java
Labels: type: bug

#224 Delete setLabel from ThingType
  concept/type/ThingType.java
Labels: priority: low, type: refactor

#228 Update automation.yml to include `release` dependencies
  .grabl/automation.yml
Labels: priority: high, type: feature

#229 Throw correct exception type while constructing session and transaction
  rpc/RPCSession.java
  rpc/RPCTransaction.java
Labels: type: bug

#232 Supports Grakn Cluster failover functionality
  .grabl/automation.yml
  BUILD
  Grakn.java
  GraknClient.java
  common/exception/ErrorMessage.java
  dependencies/graknlabs/repositories.bzl
  rpc/Address.java
  rpc/RPCDatabaseManager.java
  rpc/RPCSession.java
  rpc/RPCTransaction.java
  test/behaviour/connection/ConnectionSteps.java
  test/deployment/src/test/java/application/MavenApplicationTest.java
  test/integration/BUILD
  test/integration/ClientQueryTest.java
Labels: type: feature

#236 Make the exception message when unable to connect to the server more descriptive
  common/exception/ErrorMessage.java
  common/exception/GraknClientException.java
  rpc/RPCDatabaseManager.java
  rpc/RPCSession.java
  rpc/RPCTransaction.java
Labels: type: refactor

#237 Close session when session pulse indicates server is unavailable
  rpc/RPCSession.java
Labels: type: bug

#238 Add ability to retrieve all rules
  dependencies/graknlabs/repositories.bzl
  logic/LogicManager.java
  logic/impl/RuleImpl.java
  test/integration/ClientQueryTest.java
Labels: priority: medium, type: feature

#239 Fix console warnings caused by out of date dependency
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
Labels: type: bug

#230 Upgrade GraqlSteps (BDD) to Grakn 2.0
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  test/behaviour/graql/GraqlSteps.java
Labels: priority: medium, type: refactor

#244 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build

#243 Improve failover mechanism for primary and secondary replica connections
  Grakn.java
  GraknClient.java
  GraknOptions.java
  GraknProtoBuilder.java
  common/exception/ErrorMessage.java
  common/exception/GraknClientException.java
  common/tracing/TracingProtoBuilder.java
  concept/answer/Numeric.java
  dependencies/graknlabs/repositories.bzl
  query/QueryManager.java
  rpc/RPCDatabaseManager.java
  rpc/RPCSession.java
  rpc/RPCTransaction.java
Labels: type: feature

#247 Improve type safety of Grakn.Client.session
  Grakn.java
  GraknBase.java
  GraknClient.java
Labels: priority: medium, type: refactor

#249 Rename RPCClient to RPCGraknClient for consistency
  GraknClient.java
  rpc/RPCGraknClient.java
  rpc/RPCSession.java
  rpc/cluster/RPCGraknClientCluster.java
  rpc/cluster/RPCSessionCluster.java
Labels: priority: medium, type: refactor

#252 Add support for setting prefetch, session timeout, and schema lock timeout in GraknOptions
  GraknOptions.java
  GraknProtoBuilder.java
  common/exception/ErrorMessage.java
Labels: type: feature

#253 Support Graql update query
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  query/QueryManager.java
Labels: priority: high, type: feature
