Repository typedb/typedb-driver, pull requests merged in 2021-03, with the labels that each got.

#291 Add parallel option
  GraknOptions.java
  common/proto/OptionsProtoBuilder.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: feature

#290 Parallelise Graql Definable tests
  .grabl/automation.yml
  common/exception/ErrorMessage.java
Labels: priority: medium, type: build

#294 Handle gRPC's StatusRuntimeException with status UNKNOWN
  rpc/cluster/FailsafeTask.java
Labels: type: bug

#293 Add 'getType' to local Thing concepts
  concept/proto/ConceptProtoBuilder.java
  concept/thing/Attribute.java
  concept/thing/Entity.java
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/EntityImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  test/behaviour/concept/thing/ThingSteps.java
  test/behaviour/concept/thing/attribute/AttributeSteps.java
  test/behaviour/concept/thing/entity/EntitySteps.java
  test/behaviour/concept/thing/relation/RelationSteps.java
  test/behaviour/graql/GraqlSteps.java
Labels: priority: high, type: feature

#295 Fix possible error failing over any-replica sessions
  .bazelrc
  common/exception/GraknClientException.java
  rpc/cluster/FailsafeTask.java
  test/behaviour/graql/GraqlSteps.java
Labels: priority: medium, type: bug

#296 Delete getValueType from Attribute
  concept/thing/Attribute.java
  concept/thing/impl/AttributeImpl.java
  test/behaviour/concept/thing/attribute/AttributeSteps.java
  test/behaviour/graql/GraqlSteps.java
Labels: priority: low, type: feature

#297 Update Grakn artifacts
  dependencies/graknlabs/artifacts.bzl
Labels: dependencies, priority: medium, type: build

#298 Rename timeout options to include units (millis)
  GraknOptions.java
  common/proto/OptionsProtoBuilder.java
Labels: priority: low, type: refactor

#301 Introduced TransactionRequestBatcher to Increase Throughput
  GraknClient.java
  common/exception/ErrorMessage.java
  common/proto/OptionsProtoBuilder.java
  common/proto/ProtoBuilder.java
  concept/ConceptManager.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  logic/LogicManager.java
  query/QueryManager.java
  rpc/ClientRPC.java
  rpc/QueryFuture.java
  rpc/ResponseIterator.java
  rpc/SessionRPC.java
  rpc/SynchronizedStreamObserver.java
  rpc/TransactionRPC.java
  rpc/cluster/ClientClusterRPC.java
  rpc/common/TransactionRequestBatcher.java
  test/deployment/src/test/java/application/MavenApplicationTest.java
Labels: type: feature

#299 On transaction failover, transfer options to the new session
  .gitignore
  GraknClient.java
  rpc/SessionRPC.java
  rpc/TransactionRPC.java
  rpc/cluster/SessionClusterRPC.java
Labels: priority: medium, type: bug

#303 Clear up redundant methods, reduce code duplication
  api/GraknOptions.java
  api/concept/type/AttributeType.java
  cluster/ClusterDatabaseManager.java
  common/GraknClientException.java
  concept/ConceptImpl.java
  concept/answer/ConceptMapImpl.java
  concept/answer/NumericImpl.java
  concept/thing/AttributeImpl.java
  concept/thing/ThingImpl.java
  concept/type/AttributeTypeImpl.java
  concept/type/ThingTypeImpl.java
  concept/type/TypeImpl.java
  core/CoreClient.java
  core/CoreDatabaseManager.java
  stream/BidirectionalStream.java
  stream/ResponseIterator.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
Labels: priority: low, type: refactor

#304 New Database.schema(), resilient GraknStub, and update Protocol Architecture
  api/GraknOptions.java
  api/concept/type/AttributeType.java
  api/database/Database.java
  api/database/DatabaseManager.java
  cluster/ClusterClient.java
  cluster/ClusterDatabase.java
  cluster/ClusterDatabaseManager.java
  cluster/FailsafeTask.java
  common/BUILD
  common/exception/ErrorMessage.java
  common/exception/GraknClientException.java
  common/rpc/GraknStub.java
  common/rpc/RequestBuilder.java
  concept/ConceptImpl.java
  concept/ConceptManagerImpl.java
  concept/answer/ConceptMapImpl.java
  concept/answer/NumericImpl.java
  concept/thing/AttributeImpl.java
  concept/thing/RelationImpl.java
  concept/thing/ThingImpl.java
  concept/type/AttributeTypeImpl.java
  concept/type/EntityTypeImpl.java
  concept/type/RelationTypeImpl.java
  concept/type/RoleTypeImpl.java
  concept/type/ThingTypeImpl.java
  concept/type/TypeImpl.java
  core/CoreClient.java
  core/CoreDatabase.java
  core/CoreDatabaseManager.java
  core/CoreSession.java
  core/CoreTransaction.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  logic/LogicManagerImpl.java
  logic/RuleImpl.java
  query/QueryManagerImpl.java
  stream/BidirectionalStream.java
  stream/RequestTransmitter.java
  stream/ResponseCollector.java
  stream/ResponseIterator.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
Labels: priority: high, type: feature, type: refactor

#306 Merge all JARs for deployment
  BUILD
  api/BUILD
  cluster/BUILD
  common/BUILD
  concept/BUILD
  core/BUILD
  dependencies/graknlabs/repositories.bzl
  logic/BUILD
  query/BUILD
  stream/BUILD
Labels: type: build, type: refactor

#308 Fix error running Graql Update and clean up Concept package
  api/concept/type/AttributeType.java
  common/rpc/RequestBuilder.java
  concept/ConceptImpl.java
  concept/answer/ConceptMapImpl.java
  concept/thing/RelationImpl.java
  concept/type/AttributeTypeImpl.java
  concept/type/EntityTypeImpl.java
  concept/type/RelationTypeImpl.java
  concept/type/RoleTypeImpl.java
  concept/type/ThingTypeImpl.java
  concept/type/TypeImpl.java
  logic/RuleImpl.java
  query/QueryManagerImpl.java
Labels: priority: medium, type: bug

#310 Upgrade assemble_maven to use rewritten rule
  BUILD
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: high, type: build, type: refactor

#311 Fix deploying client-java to Maven
  dependencies/graknlabs/repositories.bzl
Labels: priority: blocker, type: bug, type: build

#309 Delete unnecessary try-catch in CoreSession
  cluster/ClusterClient.java
  cluster/ClusterDatabase.java
  cluster/ClusterDatabaseManager.java
  cluster/FailsafeTask.java
  common/rpc/RequestBuilder.java
  core/CoreSession.java
  core/CoreTransaction.java
  dependencies/graknlabs/repositories.bzl
  test/behaviour/graql/GraqlSteps.java
Labels: priority: low, type: refactor

#312 Serialised the closing of request dispatchers
  stream/RequestTransmitter.java
Labels: type: bug

#307 Implement Explanations
  api/answer/ConceptMap.java
  api/logic/Explanation.java
  api/query/QueryManager.java
  common/exception/ErrorMessage.java
  common/rpc/RequestBuilder.java
  concept/answer/ConceptMapImpl.java
  concept/thing/ThingImpl.java
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  logic/BUILD
  logic/ExplanationImpl.java
  query/BUILD
  query/QueryManagerImpl.java
  stream/BidirectionalStream.java
  stream/ResponsePartIterator.java
  test/integration/ClientQueryTest.java
Labels: priority: high

#313 Update Maven snippet in README and specify Java 11
  README.md
Labels: type: documentation
