Repository typedb/typedb-driver, pull requests merged in 2022-01, with the labels that each got.

#367 Propagate exceptions throughout transactions
  .grabl/automation.yml
  VERSION
  connection/TypeDBTransactionImpl.java
  dependencies/vaticle/repositories.bzl
  stream/BidirectionalStream.java
  stream/ResponseCollector.java
  stream/ResponsePartIterator.java
Labels: type: refactor, priority: blocker

#368 Store error on transaction stream
  connection/TypeDBTransactionImpl.java
  stream/BidirectionalStream.java
  stream/ResponseCollector.java
  stream/ResponsePartIterator.java
Labels: type: refactor, priority: high

#369 Don't delete response collectors in a transaction
  VERSION
  common/exception/ErrorMessage.java
  stream/BidirectionalStream.java
  stream/ResponseCollector.java
  stream/ResponsePartIterator.java
  test/integration/ClientQueryTest.java
Labels: type: bug, priority: high
