Repository typedb/typedb-driver, pull requests merged in 2023-11, with the labels that each got.

#514 Switch to our patched version of rules_rust (based off v0.30.0)
  dependencies/vaticle/repositories.bzl
  rust/BUILD
  rust/docs/connection/Database.adoc
  tool/docs/rust/RustDocsParser.kt
  tool/docs/rust/rules.bzl
Labels: type: build, dependencies

#525 Add untyped value getter for Java values and fix Python type hints
  java/api/concept/value/Value.java
  java/concept/value/ValueImpl.java
  java/docs/data/Value.adoc
  python/docs/schema/Type.adoc
  python/typedb/api/concept/type/type.py
  python/typedb/concept/type/thing_type.py
Labels: type: bug, priority: high

#526 Silence send errors in network callbacks when receiver dropped
  rust/src/common/error.rs
  rust/src/connection/network/transmitter/response_sink.rs
Labels: type: refactor, priority: medium

#529 Generate Rust documentation tabs and italics correctly
  java/docs/connection/TypeDBCredential.adoc
  java/docs/schema/Concept.Transitivity.adoc
  java/docs/session/TypeDBSession.Type.adoc
  java/docs/transaction/TypeDBTransaction.Type.adoc
  python/docs/connection/TypeDBCredential.adoc
  python/docs/errors/TypeDBDriverException.adoc
  python/docs/schema/Transitivity.adoc
  python/docs/session/SessionType.adoc
  python/docs/session/TypeDBOptions.adoc
  python/docs/transaction/TransactionType.adoc
  rust/docs/answer/ConceptMap.adoc
  rust/docs/answer/Trait_Promise.adoc
  rust/docs/connection/Connection.adoc
  rust/docs/connection/Credential.adoc
  rust/docs/connection/User.adoc
  rust/docs/data/Trait_AttributeAPI.adoc
  rust/docs/data/Trait_RelationAPI.adoc
  rust/docs/data/Trait_ThingAPI.adoc
  rust/docs/logic/Trait_RuleAPI.adoc
  rust/docs/schema/Trait_AttributeTypeAPI.adoc
  rust/docs/schema/Trait_EntityTypeAPI.adoc
  rust/docs/schema/Trait_RelationTypeAPI.adoc
  rust/docs/schema/Trait_RoleTypeAPI.adoc
  rust/docs/schema/Trait_ThingTypeAPI.adoc
  rust/docs/session/Options.adoc
  rust/docs/transaction/QueryManager.adoc
  rust/src/common/promise_async.rs
  tool/docs/dataclasses/Class.kt
  tool/docs/rust/RustDocsParser.kt
  tool/docs/util/Util.kt
Labels: type: documentation
