Repository typedb/typedb-driver, pull requests merged in 2023-05, with the labels that each got.

#417 Check BDD value equality using native types
  dependencies/vaticle/repositories.bzl
  test/behaviour/typeql/TypeQLSteps.java
Labels: type: feature, priority: high

#409 Introduce Values to support expressions
  .factory/automation.yml
  api/concept/Concept.java
  api/concept/type/AttributeType.java
  api/concept/type/ThingType.java
  api/concept/type/Type.java
  api/concept/value/Value.java
  common/exception/ErrorMessage.java
  common/rpc/RequestBuilder.java
  concept/ConceptImpl.java
  concept/thing/AttributeImpl.java
  concept/type/AttributeTypeImpl.java
  concept/type/ThingTypeImpl.java
  concept/value/ValueImpl.java
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/behaviour/concept/thing/attribute/AttributeSteps.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
  test/behaviour/config/Parameters.java
  test/behaviour/typeql/TypeQLSteps.java
  test/behaviour/typeql/language/expression/BUILD
  test/behaviour/typeql/language/expression/ExpressionTest.java
  test/behaviour/util/Util.java
  test/integration/ClientQueryTest.java
Labels: type: feature

#421 Introduce protocol versioning
  common/exception/ErrorMessage.java
  common/exception/TypeDBClientException.java
  common/rpc/RequestBuilder.java
  common/rpc/TypeDBStub.java
  connection/TypeDBClientImpl.java
  connection/cluster/ClusterClient.java
  connection/cluster/ClusterServerClient.java
  connection/core/CoreClient.java
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
Labels: type: feature, priority: high

#415 Update release notes workflow
  .factory/automation.yml
  BUILD
  RELEASE_NOTES_LATEST.md
  dependencies/vaticle/repositories.bzl
  tool/release/BUILD
  tool/release/create_notes.sh
Labels: priority: medium, type: documentation
