Repository typedb/typedb-driver, pull requests merged in 2023-10, with the labels that each got.

#462 Update pest 2.4.0 => 2.7.4
  RELEASE_TEMPLATE.md
  dependencies/vaticle/repositories.bzl
  java/BUILD
  java/README.md
  nodejs/README.md
  nodejs/package.json
  python/README.md
  rust/BUILD
  rust/README.md
Labels: type: build, priority: blocker, dependencies, domain: build

#464 Update VERSION and depedencies to 2.24.11
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  README.md
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/vaticle/repositories.bzl
  nodejs/README.md
  rust/README.md
Labels: priority: blocker, domain: build

#469 Merge to master for 2.24.14 release
  README.md
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/vaticle/repositories.bzl
  nodejs/connection/TypeDBDriverImpl.ts
Labels: priority: blocker, domain: build

#492 Merge to master for 2.24.15 release
  .github/CODEOWNERS
  RELEASE_NOTES_LATEST.md
  VERSION
  java/common/Loader.java
Labels: priority: blocker

#496 Remove stray factory dependency
  .factory/automation.yml
Labels: type: build, priority: blocker

#499 Update TLS certificates for client tests
  tool/test/resources/BUILD
  tool/test/resources/encryption/ext-grpc-certificate.pem
  tool/test/resources/encryption/ext-grpc-private-key.pem
  tool/test/resources/encryption/ext-grpc-root-ca.pem
  tool/test/resources/encryption/int-grpc-certificate.pem
  tool/test/resources/encryption/int-grpc-private-key.pem
  tool/test/resources/encryption/int-grpc-root-ca.pem
  tool/test/resources/encryption/int-zmq-private-key
  tool/test/resources/encryption/int-zmq-public-key
  tool/test/resources/encryption/keystore.pkcs12
Labels: type: bug, priority: high

#500 Fix filenames with incorrect symbols for Windows
  .factory/automation.yml
  nodejs/docs/Stream_T_.adoc
  tool/docs/nodejs/NodejsDocsParser.kt
Labels: type: bug, priority: blocker

#498 Wrap native exceptions with python driver exception
  c/swig/typedb_driver_python.swg
  java/concept/type/ThingTypeImpl.java
  python/docs/TypeDBDriverException.adoc
  python/docs/TypeDBDriverExceptionExt.adoc
  python/typedb/api/concept/concept.py
  python/typedb/api/concept/value/value.py
  python/typedb/api/connection/credential.py
  python/typedb/api/connection/options.py
  python/typedb/common/exception.py
  python/typedb/common/iterator_wrapper.py
  python/typedb/common/native_wrapper.py
  python/typedb/concept/answer/concept_map.py
  python/typedb/concept/answer/concept_map_group.py
  python/typedb/concept/answer/numeric.py
  python/typedb/concept/answer/numeric_group.py
  python/typedb/concept/concept.py
  python/typedb/concept/concept_factory.py
  python/typedb/concept/concept_manager.py
  python/typedb/concept/thing/attribute.py
  python/typedb/concept/thing/relation.py
  python/typedb/concept/thing/thing.py
  python/typedb/concept/type/attribute_type.py
  python/typedb/concept/type/entity_type.py
  python/typedb/concept/type/relation_type.py
  python/typedb/concept/type/role_type.py
  python/typedb/concept/type/thing_type.py
  python/typedb/concept/value/value.py
  python/typedb/connection/database.py
  python/typedb/connection/database_manager.py
  python/typedb/connection/driver.py
  python/typedb/connection/session.py
  python/typedb/connection/transaction.py
  python/typedb/logic/explanation.py
  python/typedb/logic/logic_manager.py
  python/typedb/logic/rule.py
  python/typedb/query/query_manager.py
  python/typedb/user/user.py
  python/typedb/user/user_manager.py
Labels: type: refactor, priority: high

#505 Document driver entry points
  .factory/automation.yml
  java/BUILD
  java/api/BUILD
  java/api/concept/thing/Attribute.java
  java/docs/connection/TypeDB.adoc
  java/docs/data/Attribute.adoc
  java/docs_structure.bzl
  nodejs/api/concept/thing/Attribute.ts
  nodejs/docs/connection/TypeDB.adoc
  nodejs/docs/data/Attribute.adoc
  python/docs/TypeDBDriverException.adoc
  python/docs/connection/TypeDB.adoc
  python/docs/data/Attribute.adoc
  python/docs_structure.bzl
  python/tests/integration/test_typedb.py
  python/typedb/api/concept/thing/attribute.py
  rust/docs/data/Attribute.adoc
  rust/src/concept/thing.rs
  tool/docs/dataclasses/Class.kt
  tool/docs/java/JavaDocsParser.kt
  tool/docs/nodejs/NodejsDocsParser.kt
  tool/docs/python/PythonDocsParser.kt
  tool/docs/rust/RustDocsParser.kt
Labels: priority: blocker

#502 Move CircleCI jobs for MacOS x86_64 drivers to run on mac arm64 machines
  .circleci/config.yml
  .circleci/windows/git.patch
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
  tool/test/BUILD
  tool/test/EchoJavaHome.java
  tool/test/start-core-server.sh
  tool/test/start-enterprise-servers.sh
Labels: type: build, domain: build
