Repository typedb/typedb-driver, pull requests merged in 2023-03, with the labels that each got.

#400 Cluster password policy and user management support
  api/user/User.java
  api/user/UserManager.java
  common/rpc/RequestBuilder.java
  connection/cluster/ClusterServerStub.java
  connection/cluster/ClusterUser.java
  connection/cluster/ClusterUserManager.java
  dependencies/vaticle/repositories.bzl
  test/behaviour/connection/user/UserSteps.java
Labels: type: feature, priority: high

#405 JSON serialization fixes
  dependencies/vaticle/repositories.bzl
  test/behaviour/concept/serialization/BUILD
  test/behaviour/concept/serialization/json/BUILD
  test/behaviour/concept/serialization/json/JSONSteps.java
  test/behaviour/concept/serialization/json/JSONTest.java
Labels: type: refactor, priority: medium

#406 Add API to retrieve current user
  api/TypeDBClient.java
  connection/cluster/ClusterClient.java
Labels: type: feature, priority: medium
