Repository typedb/typedb-driver, pull requests merged in 2023-04, with the labels that each got.

#407 Define password expiry in terms of seconds
  api/user/User.java
  connection/cluster/ClusterUser.java
  dependencies/vaticle/repositories.bzl
Labels: type: refactor, priority: high

#408 TypeDB Cluster Authentication Behaviour Tests
  .factory/automation.yml
  common/exception/ErrorMessage.java
  common/exception/TypeDBClientException.java
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/behaviour/BehaviourTest.java
  test/behaviour/connection/BUILD
  test/behaviour/connection/ConnectionStepsBase.java
  test/behaviour/connection/ConnectionStepsCluster.java
  test/behaviour/connection/ConnectionStepsCore.java
  test/behaviour/connection/user/BUILD
  test/behaviour/connection/user/UserSteps.java
Labels: type: feature, priority: high

#412 Implement new BDD connection opening syntax
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
  test/behaviour/config/Parameters.java
  test/behaviour/connection/ConnectionStepsBase.java
  test/behaviour/connection/ConnectionStepsCluster.java
  test/behaviour/connection/ConnectionStepsCore.java
Labels: priority: high

#413 Add behaviour test step definition for retrieving the currently connected user
  dependencies/vaticle/repositories.bzl
  test/behaviour/connection/user/UserSteps.java
Labels: type: feature, priority: medium
