Repository typedb/typedb-driver, pull requests merged in 2023-12, with the labels that each got.

#530 Session callbacks: on reopen, persistent on close; FFI bug fixes
  c/src/query.rs
  c/src/session.rs
  c/src/transaction.rs
  c/typedb_driver.i
  dependencies/vaticle/repositories.bzl
  java/api/TypeDBSession.java
  java/api/TypeDBTransaction.java
  java/api/answer/ConceptMap.java
  java/concept/answer/ConceptMapImpl.java
  java/connection/TypeDBSessionImpl.java
  java/docs/answer/ConceptMap.adoc
  java/docs/session/TypeDBSession.adoc
  java/docs/transaction/TypeDBTransaction.adoc
  nodejs/api/answer/ConceptMap.ts
  nodejs/api/connection/TypeDBSession.ts
  nodejs/api/connection/TypeDBTransaction.ts
  nodejs/concept/answer/ConceptMapImpl.ts
  nodejs/connection/TypeDBDatabaseImpl.ts
  nodejs/connection/TypeDBSessionImpl.ts
  nodejs/connection/TypeDBTransactionImpl.ts
  nodejs/docs/answer/ConceptMap.adoc
  nodejs/docs/session/TypeDBSession.adoc
  nodejs/docs/transaction/TypeDBTransaction.adoc
  nodejs/stream/BidirectionalStream.ts
  python/docs/answer/ConceptMap.adoc
  python/docs/session/TypeDBSession.adoc
  python/docs/transaction/TypeDBTransaction.adoc
  python/typedb/api/answer/concept_map.py
  python/typedb/api/connection/session.py
  python/typedb/api/connection/transaction.py
  python/typedb/concept/answer/concept_map.py
  python/typedb/connection/session.py
  rust/docs/answer/Trait_Promise.adoc
  rust/docs/errors/ConnectionError.adoc
  rust/docs/errors/InternalError.adoc
  rust/docs/session/Options.adoc
  rust/docs/session/Session.adoc
  rust/docs/transaction/Transaction.adoc
  rust/src/common/error.rs
  rust/src/common/options.rs
  rust/src/common/promise_sync.rs
  rust/src/connection/connection.rs
  rust/src/connection/message.rs
  rust/src/connection/network/proto/concept.rs
  rust/src/connection/network/proto/logic.rs
  rust/src/connection/network/proto/message.rs
  rust/src/connection/network/stub.rs
  rust/src/connection/network/transmitter/response_sink.rs
  rust/src/connection/network/transmitter/transaction.rs
  rust/src/connection/transaction_stream.rs
  rust/src/database/database.rs
  rust/src/database/database_manager.rs
  rust/src/database/session.rs
  rust/src/transaction/mod.rs
  rust/src/user/user.rs
  rust/src/user/user_manager.rs
  rust/tests/behaviour/connection/session/steps.rs
  rust/tests/behaviour/connection/transaction/steps.rs
  rust/tests/integration/queries.rs
Labels: type: bug, type: feature, priority: high

#535 Java JNI library loading: fallback when platform not specified
  java/common/Loader.java
  java/common/exception/ErrorMessage.java
Labels: type: bug, priority: high, domain: FFI

#541 C++ driver UX improvements
  .circleci/config.yml
  c/src/answer.rs
  c/typedb_driver.i
  cpp/include/typedb/answer/concept_map.hpp
  cpp/include/typedb/answer/concept_map_group.hpp
  cpp/include/typedb/answer/value_group.hpp
  cpp/include/typedb/common/iterator.hpp
  cpp/include/typedb/concept/concept.hpp
  cpp/include/typedb/concept/thing/thing.hpp
  cpp/include/typedb/concept/type/attribute_type.hpp
  cpp/include/typedb/concept/type/role_type.hpp
  cpp/include/typedb/concept/type/thing_type.hpp
  cpp/include/typedb/concept/type/type.hpp
  cpp/include/typedb/connection/driver.hpp
  cpp/include/typedb/database/database.hpp
  cpp/include/typedb/logic/explainable.hpp
  cpp/include/typedb/logic/explanation.hpp
  cpp/include/typedb/logic/rule.hpp
  cpp/include/typedb/query/query_manager.hpp
  cpp/include/typedb/user/user_manager.hpp
  cpp/lib/answer/concept_map.cpp
  cpp/lib/answer/concept_map_group.cpp
  cpp/lib/answer/value_group.cpp
  cpp/lib/common/macros.hpp
  cpp/lib/common/utils.hpp
  cpp/lib/concept/concept.cpp
  cpp/lib/concept/concept_factory.cpp
  cpp/lib/concept/concept_factory.hpp
  cpp/lib/concept/thing/relation.cpp
  cpp/lib/concept/thing/thing.cpp
  cpp/lib/concept/type/attribute_type.cpp
  cpp/lib/concept/type/role_type.cpp
  cpp/lib/concept/type/thing_type.cpp
  cpp/lib/connection/driver.cpp
  cpp/lib/database/database.cpp
  cpp/lib/logic/explainable.cpp
  cpp/lib/logic/explanation.cpp
  cpp/lib/logic/rule.cpp
  cpp/lib/user/user_manager.cpp
  cpp/test/assembly/test.cpp
  cpp/test/behaviour/steps/cloud_steps.cpp
  cpp/test/behaviour/steps/common/concept/thingapi_steps.cpp
  cpp/test/behaviour/steps/common/concept/thingtype_steps.cpp
  cpp/test/behaviour/steps/common/database_steps.cpp
  cpp/test/behaviour/steps/common/user_steps.cpp
  cpp/test/behaviour/steps/core_steps.cpp
  cpp/test/integration/test.cpp
Labels: type: feature, type: refactor

#551 Release with Ubuntu 18.04 in to lower GLIBC requirement to 2.27.0
  .circleci/config.yml
  c/tests/assembly/CMakeLists.txt
  cpp/test/assembly/CMakeLists.txt
  python/python_versions.bzl
Labels: type: refactor, priority: high, domain: build

#553 Update to tonic 1.28
  dependencies/vaticle/repositories.bzl
Labels: type: bug, domain: build

#549 Fix fetch sub-query aggregation null pointer
  .circleci/config.yml
  cpp/include/typedb/answer/json.hpp
  cpp/lib/answer/json.cpp
  cpp/test/behaviour/steps/common/concept_tables.cpp
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  java/api/answer/JSON.java
  nodejs/api/answer/JSON.ts
  nodejs/concept/answer/ReadableConceptTreeImpl.ts
  nodejs/test/behaviour/util/Util.ts
  rust/docs/answer/JSON.adoc
  rust/src/answer/json.rs
  rust/src/answer/readable_concept.rs
  rust/src/connection/network/proto/concept.rs
  rust/tests/behaviour/util/mod.rs
Labels: type: bug, priority: blocker
