Repository typedb/typedb-driver, pull requests merged in 2023-08, with the labels that each got.

#431 Improve error handling with cluster connection issues
  .bazelrc
  .factory/automation.yml
  common/BUILD
  common/exception/ErrorMessage.java
  common/exception/TypeDBClientException.java
  connection/cluster/ClusterClient.java
  connection/cluster/ClusterServerClient.java
  dependencies/vaticle/artifacts.bzl
  test/integration/BUILD
  test/integration/ClientEncryptionTest.java
  test/integration/resources/dev-certificate.pem
  test/integration/resources/dev-private-key.pem
  test/integration/resources/dev-root-ca.pem
  test/integration/resources/wrong-root-ca.pem
Labels: type: feature, priority: medium

#432 Improve interaction with TypeDB cluster databases
  common/exception/TypeDBClientException.java
  connection/cluster/ClusterClient.java
  connection/cluster/ClusterDatabaseManager.java
  dependencies/vaticle/repositories.bzl
  test/integration/ClientEncryptionTest.java
Labels: type: bug, type: refactor

#436 Python-specific conversions for SWIG
  .bazelversion
  WORKSPACE
  dependencies/vaticle/repositories.bzl
  java/test/behaviour/typeql/language/insert/BUILD
  rust/BUILD
  rust/swig/typedb_client_python.swg
  rust/typedb_client.i
Labels: type: feature, priority: high, dependencies

#439 Create CircleCI configuration skeleton
  .circleci/config.yml
  .circleci/windows/dependencies.config
  .circleci/windows/prepare.bat
Labels: priority: blocker, domain: build
