Repository typedb/typedb-driver, pull requests merged in 2024-01, with the labels that each got.

#559 Merge CircleCI jobs per platform
  .circleci/config.yml
  .circleci/windows/java/test_deploy_snapshot.bat
  .circleci/windows/python/deploy_release.bat
  .circleci/windows/python/test_deploy_snapshot.bat
  python/python_versions.bzl
Labels: type: refactor, priority: high, domain: build

#558 Check server URL contains port
  .factory/automation.yml
  cpp/test/integration/test.cpp
  java/test/integration/DriverQueryTest.java
  nodejs/common/errors/ErrorMessage.ts
  nodejs/connection/TypeDBDriverImpl.ts
  nodejs/test/integration/test-connection.js
  python/tests/integration/BUILD
  python/tests/integration/test_connection.py
  rust/docs/errors/ConnectionError.adoc
  rust/src/common/address.rs
  rust/src/common/error.rs
  rust/src/connection/network/proto/concept.rs
  rust/tests/integration/queries.rs
Labels: type: feature, priority: medium

#562 Release from Amazon Linux to supports GLIBC 2.26
  .circleci/config.yml
Labels: type: build, type: refactor, priority: blocker, domain: build

#563 Increase size of Windows executor in CircleCI to XL
  .bazelrc
  .circleci/config.yml
  .circleci/windows/dependencies.config
  .circleci/windows/prepare.bat
  .circleci/windows/python/deploy_snapshot.bat
Labels: type: refactor, priority: high, domain: build

#568 Move deployment jobs from Factory CI to CIrcleCI
  .circleci/config.yml
  .factory/automation.yml
Labels: type: refactor, priority: medium, domain: build

#561 Migrate artifact hosting to cloudsmith
  .circleci/config.yml
  .circleci/windows/clib/deploy_release.bat
  .circleci/windows/clib/deploy_snapshot.bat
  .circleci/windows/cpp/deploy_release.bat
  .circleci/windows/cpp/deploy_snapshot.bat
  .circleci/windows/java/deploy_release.bat
  .circleci/windows/java/deploy_snapshot.bat
  .circleci/windows/python/deploy_snapshot.bat
  .circleci/windows/python/test_deploy_snapshot.bat
  .factory/automation.yml
  README.md
  RELEASE_NOTES_LATEST.md
  RELEASE_TEMPLATE.md
  WORKSPACE
  c/BUILD
  cpp/BUILD
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  java/BUILD
  java/README.md
  java/test/behaviour/BehaviourTest.java
  java/test/behaviour/connection/ConnectionStepsBase.java
  java/test/behaviour/connection/ConnectionStepsCloud.java
  java/test/behaviour/connection/ConnectionStepsCore.java
  java/test/deployment/pom.xml
  java/test/integration/DriverQueryTest.java
  nodejs/BUILD
  python/rules.bzl
  python/tests/deployment/requirements.txt
  rust/BUILD
Labels: domain: build

#570 Update to allow Unicode TypeQL variable names
  README.md
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  rust/tests/behaviour/query/language/steps.rs
Labels: type: feature, priority: medium

#571 Sync dependencies in CI
  .circleci/config.yml
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
  workspace-status.sh
Labels: type: build, priority: high, domain: build

#574 Fix CircleCI sync dependencies configuration mismatch
  .circleci/config.yml
  BUILD
Labels: priority: blocker, domain: build

#576 Missing trailing comma in BUILD
  BUILD
Labels: type: build, priority: blocker, domain: build

#577 Set default Python version to 3.11
  python/BUILD
  python/docs/schema/ValueType.adoc
  python/python_versions.bzl
  python/typedb/api/concept/value/value.py
Labels: type: build, priority: high

#579 Setup python3.11 CFFI in CI for sync-dependencies
  .circleci/config.yml
  .factory/automation.yml
Labels: type: build, priority: blocker, domain: build

#578 Only deploy releases to cloudsmith
  .circleci/config.yml
  .circleci/windows/clib/deploy_release.bat
  .circleci/windows/cpp/deploy_release.bat
  .circleci/windows/java/deploy_release.bat
  .circleci/windows/python/deploy_release.bat
  RELEASE_TEMPLATE.md
Labels: type: build, priority: blocker, domain: build

#573 Refactor C++ docs to reflect other docs
  cpp/docs/answer/Future__RETURN__NATIVE_PROMISE__HELPER__.adoc
  cpp/docs/answer/Iterable__NATIVE_ITER__NATIVE_T__T__HELPER__.adoc
  cpp/docs/answer/Iterator__NATIVE_ITER__NATIVE_T__T__HELPER__.adoc
  cpp/docs/answer/typedefs.adoc
  cpp/docs_structure.bzl
Labels: type: refactor

#581 Revert to python3.9 in Bazel
  .circleci/config.yml
  .factory/automation.yml
  python/BUILD
  python/python_versions.bzl
Labels: type: build, priority: blocker, domain: build

#582 Transition from standalone typedb-common to typeql/common
  .factory/automation.yml
  BUILD
  WORKSPACE
  dependencies/vaticle/repositories.bzl
  java/BUILD
  java/api/BUILD
  java/common/BUILD
  java/concept/BUILD
  java/test/behaviour/concept/thing/BUILD
  java/test/behaviour/concept/type/attributetype/BUILD
  java/test/behaviour/concept/type/thingtype/BUILD
  java/test/behaviour/connection/BUILD
  java/test/behaviour/connection/database/BUILD
  java/test/behaviour/connection/session/BUILD
  java/test/behaviour/connection/transaction/BUILD
  java/test/behaviour/query/BUILD
  java/test/behaviour/util/BUILD
  java/test/integration/BUILD
Labels: type: refactor, priority: blocker, dependencies
