Repository typedb/typedb-driver, pull requests merged in 2024-09, with the labels that each got.

#687 Improve Decimal formatting
  rust/src/concept/value.rs
Labels: type: bug, priority: medium

#689 Enable Java driver release for 3.0
  .circleci/config.yml
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/vaticle/repositories.bzl
Labels: domain: build

#686 Fix native object ownership checks in python driver
  python/typedb/connection/database.py
  python/typedb/connection/transaction.py
Labels: domain: FFI
