Repository typedb/typedb-driver, pull requests merged in 2024-03, with the labels that each got.

#598 Add setSupertype docs to nodejs thing types
  nodejs/api/concept/type/AttributeType.ts
  nodejs/api/concept/type/EntityType.ts
  nodejs/api/concept/type/RelationType.ts
  nodejs/docs/schema/AttributeType.adoc
  nodejs/docs/schema/EntityType.adoc
  nodejs/docs/schema/RelationType.adoc
Labels: priority: medium, type: documentation

#617 Fix deadsnakes ppa in Circle CI sync-dependencies release job
  .circleci/config.yml
Labels: type: bug, priority: high, domain: build

#618 Add README for the C# driver with examples
  csharp/README.md
Labels: priority: high

#619 Fix parsing & formatting issues for C, C++ documentation
  c/docs/answer/conceptmap.adoc
  c/docs/answer/explanation.adoc
  c/docs/answer/primitives.adoc
  c/docs/answer/types.adoc
  c/docs/answer/valuegroup.adoc
  c/docs/concept/attribute.adoc
  c/docs/concept/concept.adoc
  c/docs/concept/entity.adoc
  c/docs/concept/relation.adoc
  c/docs/concept/roleplayer.adoc
  c/docs/concept/thing.adoc
  c/docs/concept/types.adoc
  c/docs/concept/value.adoc
  c/docs/connection/connection.adoc
  c/docs/connection/credential.adoc
  c/docs/connection/database.adoc
  c/docs/connection/replica.adoc
  c/docs/connection/types.adoc
  c/docs/connection/user.adoc
  c/docs/errors/error.adoc
  c/docs/errors/schemaexception.adoc
  c/docs/errors/types.adoc
  c/docs/logic/logic.adoc
  c/docs/logic/rule.adoc
  c/docs/logic/types.adoc
  c/docs/schema/annotation.adoc
  c/docs/schema/attributetype.adoc
  c/docs/schema/entitytype.adoc
  c/docs/schema/relationtype.adoc
  c/docs/schema/roletype.adoc
  c/docs/schema/transitivity.adoc
  c/docs/schema/valuetype.adoc
  c/docs/session/options.adoc
  c/docs/session/session.adoc
  c/docs/session/types.adoc
  c/docs/transaction/query.adoc
  c/docs/transaction/transaction.adoc
  c/docs/transaction/types.adoc
  c/docs_structure.bzl
  cpp/docs/connection/Credential.adoc
  cpp/docs/connection/User.adoc
  cpp/include/typedb/connection/driver.hpp
  tool/docs/c/DoxygenParserC.kt
  tool/docs/cpp/DoxygenParserCpp.kt
  tool/docs/dataclasses/Class.kt
Labels: type: documentation
