Repository typedb/typedb-driver, pull requests merged in 2024-02, with the labels that each got.

#595 Fix native calls in python driver rules api
  python/typedb/logic/rule.py
Labels: type: bug, priority: medium

#597 Fix Factory CI job names
  .factory/automation.yml
Labels: type: bug, priority: blocker, domain: build

#594 Add default options parameters for session & transaction
  cpp/docs/connection/Driver.adoc
  cpp/docs/session/Session.adoc
  cpp/include/typedb/connection/driver.hpp
  cpp/include/typedb/connection/session.hpp
Labels: type: refactor
