Repository typedb/typedb-driver, pull requests merged in 2024-05, with the labels that each got.

#645 Fix misleading cloud encryption error message
  docs/modules/ROOT/partials/rust/errors/ConnectionError.adoc
  rust/src/common/error.rs
Labels: type: refactor, priority: low

#644 Each API reference is combined in a single partial for easier preview and usage
  .factory/automation.yml
  docs/modules/ROOT/partials/c/api-reference.adoc
  docs/modules/ROOT/partials/cpp/api-reference.adoc
  docs/modules/ROOT/partials/csharp/api-reference.adoc
  docs/modules/ROOT/partials/java/api-reference.adoc
  docs/modules/ROOT/partials/nodejs/api-reference.adoc
  docs/modules/ROOT/partials/python/api-reference.adoc
  docs/modules/ROOT/partials/rust/api-reference.adoc
Labels: priority: medium, type: documentation

#647 Copy jin library from input stream rather than file
  java/common/Loader.java
Labels: type: feature

#648 Update dependencies, VERSION & release notes for 2.28.1 release
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
Labels: type: refactor

#652 JNI library loading uses a predetermined file name
  java/common/Loader.java
Labels: type: bug

#651 Turn off statistics reporting in CI
  .circleci/windows/clib/test_assembly.bat
  .circleci/windows/cpp/test_assembly.bat
  .circleci/windows/csharp/test_deploy_snapshot.bat
  .circleci/windows/java/test_deploy_snapshot.bat
  .circleci/windows/python/test_deploy_snapshot.bat
  java/test/integration/DriverQueryTest.java
  nodejs/test/integration/test-cloud-failover.js
  python/tests/integration/cloud_test_rule.bzl
  python/tests/integration/test_cloud_failover.py
  tool/test/start-cloud-servers.sh
  tool/test/start-core-server.sh
Labels: priority: high, domain: build
