Repository typedb/typedb-driver, pull requests merged in 2024-04, with the labels that each got.

#622 Update Git patch during Windows Circle CI initial job setup
  .circleci/windows/git.patch
  .circleci/windows/prepare.bat
Labels: type: bug, priority: blocker, domain: build

#626 Implement new steps for getting answers from templated get
  cpp/test/behaviour/steps/common/query_steps.cpp
  csharp/Test/Behaviour/Query/QuerySteps.cs
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  java/test/behaviour/query/QuerySteps.java
  nodejs/test/behaviour/query/QuerySteps.ts
  python/tests/behaviour/query/query_steps.py
  rust/tests/behaviour/query/language/steps.rs
Labels: type: refactor, priority: medium

#632 Deploy C# driver in a separate job
  .circleci/config.yml
  csharp/Api/BUILD
  csharp/Common/BUILD
Labels: type: build, priority: blocker, domain: build

#638 Fix C# README examples and add issues refs to recent TODOs
  .factory/automation.yml
  c/BUILD
  cpp/BUILD
  cpp/test/behaviour/steps/common/common_steps.cpp
  cpp/test/cucumber/include/cucumber_bdd/runner.hpp
  csharp/BUILD
  csharp/README.md
  csharp/Test/Behaviour/Util/UtilSteps.cs
  rust/tests/behaviour/query/reasoner/steps.rs
Labels: type: documentation

#580 Implement a method to convert a JSON object to a JSON string
  cpp/BUILD
  cpp/docs/answer/JSON.adoc
  cpp/include/typedb/answer/json.hpp
  cpp/lib/answer/json.cpp
  cpp/test/assembly/CMakeLists.txt
  cpp/test/integration/test_core.cpp
Labels: type: feature
