Repository typedb/typedb-driver, pull requests merged in 2024-12, with the labels that each got.

#720 Remove system database workaround
  dependencies/typedb/artifacts.bzl
  java/test/behaviour/connection/ConnectionStepsBase.java
  python/tests/behaviour/background/core/environment.py
  rust/tests/behaviour/steps/lib.rs
Labels: type: bug, priority: high

#718 Revert get current user API
  c/src/user_manager.rs
  c/typedb_driver.i
  docs/modules/ROOT/partials/python/connection/UserManager.adoc
  java/api/user/UserManager.java
  java/test/behaviour/connection/user/UserSteps.java
  java/user/UserManagerImpl.java
  python/tests/behaviour/connection/user/user_steps.py
  python/typedb/api/user/user.py
  python/typedb/user/user_manager.py
  rust/src/user/user_manager.rs
  rust/tests/behaviour/steps/connection/user.rs
Labels: type: bug, priority: high

#719 Move user update and delete API to the User object
  c/src/user.rs
  c/src/user_manager.rs
  c/typedb_driver.i
  dependencies/typedb/artifacts.bzl
  java/api/user/User.java
  java/api/user/UserManager.java
  java/test/behaviour/connection/ConnectionStepsBase.java
  java/test/behaviour/connection/user/UserSteps.java
  java/user/UserImpl.java
  java/user/UserManagerImpl.java
  python/tests/behaviour/background/core/environment.py
  python/tests/behaviour/connection/user/user_steps.py
  python/typedb/api/user/user.py
  python/typedb/user/user.py
  python/typedb/user/user_manager.py
  rust/src/common/info.rs
  rust/src/connection/message.rs
  rust/src/connection/network/proto/message.rs
  rust/src/connection/network/proto/user.rs
  rust/src/connection/server_connection.rs
  rust/src/user/user.rs
  rust/src/user/user_manager.rs
  rust/tests/behaviour/steps/connection/user.rs
  rust/tests/behaviour/steps/lib.rs
Labels: type: bug, priority: high

#725 Merge for release 2.29.2
  VERSION
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
Labels: domain: build

#727 Rename long to integer
  c/src/concept/concept.rs
  c/swig/typedb_driver_csharp.swg
  c/swig/typedb_driver_java.swg
  cpp/test/integration/test_core.cpp
  dependencies/typedb/artifacts.bzl
  dependencies/typedb/repositories.bzl
  docs/modules/ROOT/partials/java/concept/Concept.adoc
  docs/modules/ROOT/partials/java/data/Attribute.adoc
  docs/modules/ROOT/partials/java/data/Entity.adoc
  docs/modules/ROOT/partials/java/data/Instance.adoc
  docs/modules/ROOT/partials/java/data/Relation.adoc
  docs/modules/ROOT/partials/java/data/Value.adoc
  docs/modules/ROOT/partials/java/schema/AttributeType.adoc
  docs/modules/ROOT/partials/java/schema/EntityType.adoc
  docs/modules/ROOT/partials/java/schema/RelationType.adoc
  docs/modules/ROOT/partials/java/schema/RoleType.adoc
  docs/modules/ROOT/partials/java/schema/Type.adoc
  docs/modules/ROOT/partials/python/concept/Concept.adoc
  docs/modules/ROOT/partials/python/data/Attribute.adoc
  docs/modules/ROOT/partials/python/data/Value.adoc
  docs/modules/ROOT/partials/rust/concept/Concept.adoc
  docs/modules/ROOT/partials/rust/data/Value.adoc
  docs/modules/ROOT/partials/rust/schema/ValueType.adoc
  java/README.md
  java/api/concept/Concept.java
  java/api/concept/instance/Attribute.java
  java/api/concept/value/Value.java
  java/concept/ConceptImpl.java
  java/concept/instance/AttributeImpl.java
  java/concept/value/ValueImpl.java
  java/core_example
  java/test/behaviour/config/Parameters.java
  java/test/behaviour/query/QuerySteps.java
  java/test/integration/core/ExampleTest.java
  java/test/integration/core/ValueTest.java
  python/README.md
  python/core_example
  python/tests/behaviour/config/parameters.py
  python/tests/behaviour/query/query_steps.py
  python/tests/integration/core/test_example.py
  python/tests/integration/core/test_values.py
  python/typedb/api/concept/concept.py
  python/typedb/api/concept/instance/attribute.py
  python/typedb/api/concept/value/value.py
  python/typedb/concept/concept.py
  python/typedb/concept/instance/attribute.py
  python/typedb/concept/value/value.py
  rust/README.md
  rust/core_example
  rust/src/answer/concept_document.rs
  rust/src/concept/mod.rs
  rust/src/concept/value.rs
  rust/src/connection/network/proto/concept.rs
  rust/tests/behaviour/steps/params.rs
  rust/tests/behaviour/steps/query.rs
  rust/tests/integration/core/example.rs
Labels: type: refactor

#728 Optimise driver dispatch loop
  rust/src/connection/network/transmitter/transaction.rs
Labels: type: bug, priority: blocker
