Repository typedb/typedb-driver, pull requests merged in 2025-01, with the labels that each got.

#734 Update typedb behavior dependency and typedb server artifact to test the unblocked server features
  dependencies/typedb/artifacts.bzl
  dependencies/typedb/repositories.bzl
Labels: dependencies

#735 Introduce 3.0 cloud driver tests
  .factory/automation.yml
  java/test/behaviour/connection/BUILD
  java/test/behaviour/connection/ConnectionStepsCloud.java
  java/test/behaviour/rules.bzl
  java/test/integration/cloud/BUILD
  java/test/integration/cloud/ExampleTest.java
  python/tests/behaviour/background/cloud/environment.py
  python/tests/behaviour/behave_rule.bzl
  python/tests/integration/cloud/BUILD
  python/tests/integration/cloud/test_example.py
  python/typedb/connection/driver.py
  rust/tests/behaviour/steps/lib.rs
  rust/tests/integration/cloud/BUILD
  rust/tests/integration/cloud/example.rs
Labels: type: bug, type: build, priority: high

#736 Add 'dec' suffix to notation of 'Decimal' type
  dependencies/typedb/artifacts.bzl
  dependencies/typedb/repositories.bzl
  java/test/behaviour/query/QuerySteps.java
  java/test/integration/core/ValueTest.java
  python/tests/behaviour/query/query_steps.py
  python/tests/integration/core/test_values.py
  rust/src/concept/value.rs
  rust/tests/behaviour/steps/params.rs
Labels: type: refactor

#737 Bump version & prepare release notes for 3.0.4
  RELEASE_NOTES_LATEST.md
  VERSION
Labels: type: build, domain: build

#740 Mark query answer accessors as allocating for SWIG
  c/swig/typedb_driver_java.swg
  c/typedb_driver.i
Labels: type: bug, priority: high, domain: FFI
